### ISSUE TITLE
"Pillow is not installed."

### ISSUE THREAD

**Issue by bosmak** [Djacket/djacket#3]
```
                All set? Should we continue?  [yes|no] yes

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named PIL
Pillow is not installed.

----------------------------------------------------------------

Bad Luck! 
Please fix happened issues and run the script again.
```

But

```
[19:20:12 vagrant@djacket:/vagrant/djacket][master] $ pip3 install pillow
Requirement already satisfied (use --upgrade to upgrade): pillow in /usr/local/lib/python3.4/dist-packages
Cleaning up...

```

```
[19:30:34 vagrant@djacket:/vagrant/djacket][master] $ python3
Python 3.4.2 (default, Oct  8 2014, 10:45:20) 
[GCC 4.9.1] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PIL
>>> print('Works?')
Works?
>>> 
```

any ideia why?

---

```
if ! python -c "from PIL import Image"; then
        echo 'Pillow is not installed.';
        issue_error;
fi

```

Changed to python3 and the setup.sh worked...

So it's ok to change to py3 or i need to install py2 and install pillow there?

**Comment by moeenz** [comment]
Hello Bosmak.

Best guess I can make is that the error given in first part is because, Pillow installation is in python3 environment and it's not being available in python2. Because the line "if ! python -c 'from PIL import Image'; then" is assuming python3 is the default python environment.

About your question in the end; yes It's OK to change to python3 and install Pillow there, then installation will work correctly.

This is an issue, and I will correct it as soon as possible.
Thanks for pointing it out.
